galaxy_info:
  author: Bojan Å ernek
  description: Audiocloud NATS message broker role
  company: Distopik Ltd.
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
    - name: GenericLinux
    - name: macOS

dependencies:
  - role: common
