galaxy_info:
  description: Instance Driver Common
  author: Bojan Å ernek
  min_ansible_version: "2.9"
  license: MIT
  platforms:
    - name: macOS
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
